version: 1

formatters:
  simple:
    format: '%(asctime)s - %(filename)s - [line:%(lineno)d] - %(levelname)s: %(message)s'
    datefmt: '%F %T'

handlers:

  console:
    class: logging.StreamHandler
    # class: logging.FileHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  quandashi_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: ./log/quandashi.log
    maxBytes: 10485760 # 10MB
    backupCount: 20 #most 20 extensions
    encoding: utf8

loggers:

  quandashi:
    level: INFO
    handlers: [quandashi_file_handler]
    propagate: yes

root:
  level: DEBUG
  handlers: [console]